rm -rf android
rm -rf apex
rm -rf aspnetcore
rm -rf eiffel
rm -rf elixir
rm -rf elm
rm -rf erlang-client
rm -rf go-server
rm -rf haskell-http-client
rm -rf inflector
rm -rf jaxrs-resteasy
rm -rf jaxrs-resteasy-eap
rm -rf kotlin
rm -rf kotlin-server
rm -rf md.tar
rm -rf nodejs-server
rm -rf powershell
rm -rf python-flask
rm -rf spring
rm -rf tizen
rm -rf typescript-angular
rm -rf typescript-aurelia
